require: rubocop-rspec

AllCops:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'
    - '*/*/version.rb'
    - 'bin/*'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
RSpec/MultipleExpectations:
  Max: 2
RSpec/ExampleLength:
  Max: 10
Style/ClassCheck:
  Enabled: false
